Imported Upstream version 2.3.2~a7

diff --git a/bin/hlogin.in b/bin/hlogin.in
--- a/bin/hlogin.in
+++ b/bin/hlogin.in
@@ -1,8 +1,9 @@
 #! @EXPECT_PATH@ --
 ##
-## $Id: hlogin.in,v 1.23 2004/04/09 00:06:44 heas Exp $
+## $Id: hlogin.in,v 1.40 2006/12/08 21:28:26 heas Exp $
 ##
-## Copyright (C) 1997-2004 by Terrapin Communications, Inc.
+## @PACKAGE@ @VERSION@
+## Copyright (C) 1997-2006 by Terrapin Communications, Inc.
 ## All rights reserved.
 ##
 ## This software may be freely copied, modified and redistributed
@@ -57,9 +58,11 @@ set do_passwd 1
 set do_enapasswd 1
 # attempt at platform switching.
 set platform ""
+#
+set send_human {.4 .4 .7 .3 5}
 
 # Find the user in the ENV, or use the unix userid.
-if {[ info exists env(CISCO_USER) ] } {
+if {[ info exists env(CISCO_USER) ]} {
     set default_user $env(CISCO_USER)
 } elseif {[ info exists env(USER) ]} {
     set default_user $env(USER)
@@ -74,6 +77,9 @@ if {[ info exists env(CISCO_USER) ] } {
 	exit 1
     }
     regexp {\(([^)]*)} "$reason" junk default_user
+}
+if {[ info exists env(CLOGINRC) ]} {
+    set password_file $env(CLOGINRC)
 }
 
 # Sometimes routers take awhile to answer (the default is 10 sec)
@@ -100,13 +106,16 @@ for {set i 0} {$i < $argc} {incr i} {
 	    }
 	    set do_passwd 0
 	# VTY Password
-	} -v* -
-	-v* {
+	} -v* {
 	    if {! [  regexp .\[vV\](.+) $arg ignore passwd]} {
 		incr i
 		set passwd [ lindex $argv $i ]
 	    }
 	    set do_passwd 0
+	# Version string
+	} -V* {
+	    send_user "@PACKAGE@ @VERSION@\n"
+	    exit 0
 	# Enable Username
 	} -w* -
 	-W* {
@@ -181,8 +190,8 @@ for {set i 0} {$i < $argc} {incr i} {
 	    }
 	    if [ catch {set cmd_fd [open $cmd_file r]} reason ] {
 		send_user "\nError: $reason\n"
-		exit 1 
-	    }  
+		exit 1
+	    }
 	    set cmd_text [read $cmd_fd]
 	    close $cmd_fd
 	    set command [join [split $cmd_text \n] \;]
@@ -244,25 +253,25 @@ proc label { host } {
 # add password *	hanky-pie
 proc add {var args} { global int_$var ; lappend int_$var $args}
 proc include {args} {
-    global env 
-    regsub -all "(^{|}$)" $args {} args 
+    global env
+    regsub -all "(^{|}$)" $args {} args
     if { [ regexp "^/" $args ignore ] == 0 } {
 	set args $env(HOME)/$args
-    } 
+    }
     source_password_file $args
-}   
-    
+}
+
 proc find {var router} {
-    upvar int_$var list 
+    upvar int_$var list
     if { [info exists list] } {
 	foreach line $list {
 	    if { [string match [lindex $line 0] $router ] } {
 		return [lrange $line 1 end]
-	    }     
-	}       
-    }     
-    return {} 
-}           
+	    }
+	}
+    }
+    return {}
+}
 
 # Loads the password file.  Note that as this file is tcl, and that
 # it is sourced, the user better know what to put in there, as it
@@ -287,6 +296,7 @@ proc source_password_file { password_file } {
 }
 
 # Log into the router.
+# returns: 0 on success, 1 on failure
 proc login { router user userpswd passwd enapasswd cmethod cyphertype } {
     global spawn_id in_proc do_command do_script platform
     global prompt u_prompt p_prompt e_prompt sshcmd
@@ -295,6 +305,7 @@ proc login { router user userpswd passwd enapasswd cmethod cyphertype } {
     # try each of the connection methods in $cmethod until one is successful
     set progs [llength $cmethod]
     foreach prog [lrange $cmethod 0 end] {
+	incr progs -1
 	regexp {(telnet|ssh)(:([^[:space:]]+))*} $prog command suffix junk port
 	if [string match "telnet*" $prog] {
 	    if {"$port" == ""} {
@@ -304,28 +315,28 @@ proc login { router user userpswd passwd enapasswd cmethod cyphertype } {
 	    }
 	    if { $retval } {
 		send_user "\nError: telnet failed: $reason\n"
-		exit 1
+		return 1
 	    }
 	} elseif [string match "ssh*" $prog] {
 	    if {"$port" == ""} {
-		set retval [ catch {spawn hpuifilter -- '$sshcmd -c $cyphertype -x -l $user' $router} reason ]
+		set retval [ catch {spawn hpuifilter -- $sshcmd -c $cyphertype -x -l $user $router} reason ]
 	    } else {
 		set retval [ catch {spawn hpuifilter -- $sshcmd -c $cyphertype -p $port -x -l $user $router} reason ]
 	    }
 	    if { $retval } {
 		send_user "\nError: $sshcmd failed: $reason\n"
-		exit 1
+		return 1
 	    }
 	} elseif ![string compare $prog "rsh"] {
-	    if [ catch {spawn hpuifilter rsh -l $user $router} reason ] {
-		send_user "\nError: rsh failed: $reason\n"
-		exit 1
+	    send_error "\nError: unsupported method: rsh\n"
+	    if { $progs == 0 } {
+		return 1
 	    }
+	    continue;
 	} else {
-	    puts "\nError: unknown connection method: $prog"
+	    send_user "\nError: unknown connection method: $prog\n"
 	    return 1
 	}
-	incr progs -1
 	sleep 0.3
 
 	# This helps cleanup each expect clause.
@@ -367,11 +378,6 @@ proc login { router user userpswd passwd enapasswd cmethod cyphertype } {
 		send_user "\nError: Connection Refused ($prog)\n"; return 1
 	    }
 	}
-	eof { send_user "\nError: Couldn't login\n"; wait; return 1 }
-	-nocase "unknown host\r" {
-	    catch {close};
-	    send_user "\nError: Unknown host\n"; wait; return 1
-	}
 	"Host is unreachable" {
 	    catch {close};
 	    send_user "\nError: Host Unreachable!\n"; wait; return 1
@@ -392,12 +398,21 @@ proc login { router user userpswd passwd enapasswd cmethod cyphertype } {
 	    send "no\r"
 	    send_user "\nError: host key mismatch for $router.  Update the SSH known_hosts file accordingly.\n"
 	    return 1 }
+	eof { send_user "\nError: Couldn't login\n"; wait; return 1 }
+	-nocase "unknown host\r" {
+	    catch {close};
+	    send_user "\nError: Unknown host\n"; wait; return 1
+	}
 	-re "$u_prompt"	{ send "$user\r"
 	    expect {
 		eof			{ send_user "\nError: Couldn't login\n"; wait; return 1 }
 		"Login invalid"		{ send_user "\nError: Invalid login\n"; vatch {close}; wait; return 1 }
 		-re "$p_prompt"		{ send "$userpswd\r" }
 		"$prompt"		{ set in_proc 0; return 0 }
+		"Press any key to continue" {
+					  send " "
+					  exp_continue
+					}
 	    }
 	    exp_continue
 	}
@@ -408,9 +423,18 @@ proc login { router user userpswd passwd enapasswd cmethod cyphertype } {
 		send "$passwd\r"
 	    }
 	    expect {
-		eof		{ send_user "\nError: Couldn't login\n"; wait; return 1 }
+		eof		{ send_user "\nError: Couldn't login\n";
+				  wait;
+				  return 1
+				}
+		"Press any key to continue" {
+				  send " ";
+				  exp_continue
+				}
 		-re "$e_prompt"	{ send "$enapasswd\r" }
-		"$prompt"	{ set in_proc 0; return 0 }
+		"$prompt"	{ set in_proc 0;
+				  return 0
+				}
 	    }
 	    exp_continue
 	}
@@ -454,16 +478,14 @@ proc run_commands { prompt command } {
     global in_proc platform
     set in_proc 1
 
-    # If the prompt is (enable), then we are on a switch and the
-    # command is "set length 0"; otherwise its "term length 0".
-    # skip if its and extreme.
+    # Turn off the pager and escape regex meta characters in the $prompt
     send "no page\r"
     regsub -all "\[)(]" $prompt {\\&} reprompt
-	expect {
-	    -re $reprompt	{}
-	    -re "\[\n\r]+"	{ exp_continue }
-	}
-    # this is the only way i see to get rid for more prompts in o/p..grrrrr
+    expect {
+	-re $reprompt	{}
+	-re "\[\n\r]+"	{ exp_continue }
+    }
+    # this is the only way i see to get rid of more prompts in o/p..grrrrr
     log_user 0
     # Is this a multi-command?
     if [ string match "*\;*" "$command" ] {
@@ -491,6 +513,10 @@ proc run_commands { prompt command } {
 						}
 		-re "^<-+ More -+>\[^\n\r]*"	{ send " "
 						  exp_continue }
+		-re "^-+ MORE -+\[^\n\r]*"	{ send " "
+						  exp_continue }
+		-re "^-+More-+\[^\n\r]*"	{ send " "
+						  exp_continue }
 		-re "\b+"			{ exp_continue }
 	    }
 	}
@@ -516,11 +542,13 @@ proc run_commands { prompt command } {
 						  exp_continue }
 		-re "^-+ MORE -+\[^\n\r]*"	{ send " "
 						  exp_continue }
+		-re "^-+More-+\[^\n\r]*"	{ send " "
+						  exp_continue }
 		-re "\b+"			{ exp_continue }
 	}
     }
     log_user 1
-    send "exit\r"
+    send -h "exit\r"
     expect {
 	"Do you want to save current configuration"	{
 						  send "n\r"
@@ -536,10 +564,12 @@ proc run_commands { prompt command } {
 						}
 	-re "\[\r\n]+"				{ exp_continue }
 	-re "^.+>"				{
-						  send "exit\r"
+						  send -h "exit\r"
 						  exp_continue
 						}
-	timeout					{ return 0 }
+	timeout					{ catch {close}; wait
+						  return 0
+						}
 	eof					{ return 0 }
     }
     set in_proc 0
@@ -593,6 +623,9 @@ foreach router [lrange $argv $i end] {
       }
       set passwd [join [lindex $pswd 0] ""]
       set enapasswd [join [lindex $pswd 1] ""]
+    } else {
+	set passwd $userpasswd
+	set enapasswd $enapasswd
     }
 
     # Figure out username
@@ -655,9 +688,9 @@ foreach router [lrange $argv $i end] {
     set cmethod [find method $router]
     if { "$cmethod" == "" } { set cmethod {{telnet} {ssh}} }
 
-    # Figure out the SSH executable name  
-    set sshcmd [find sshcmd $router]  
-    if { "$sshcmd" == "" } { set sshcmd {ssh} }  
+    # Figure out the SSH executable name
+    set sshcmd [find sshcmd $router]
+    if { "$sshcmd" == "" } { set sshcmd {ssh} }
 
     # Adjust our path to find hpuifilter
     regexp {(.*)/[^/]+} $argv0 junk hpf_path
@@ -672,17 +705,17 @@ foreach router [lrange $argv $i end] {
     if { $enable } {
 	if {[do_enable $enauser $enapasswd]} {
 	    if { $do_command || $do_script } {
-		close; wait
+		catch {close}; catch {wait}
 		continue
 	    }
 	}
     }
     # we are logged in, now figure out the full prompt
-    send "\r"   
-    expect {    
+    send "\r"
+    expect {
 	-re "\[\r\n]+"		{ exp_continue; }
 	-re "^.+$prompt"	{ set prompt $expect_out(0,string); }
-    }       
+    }
 
     if { $do_command } {
 	if {[run_commands $prompt $command]} {
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -41,16 +41,54 @@ AC_C_STRINGIZE
 
 # check includes/headers
 AC_HEADER_STDC
-AC_CHECK_HEADERS(limits.h memory.h siginfo.h string.h strings.h unistd.h)
-
-AC_CHECK_HEADERS(errno.h fcntl.h sys/types.h sys/wait.h)
-dnl AC_CHECK_HEADERS(errno.h stdlib.h sys/types.h sys/wait.h)
-dnl AC_CHECK_HEADERS(malloc.h)
+AC_CHECK_HEADERS(errno.h fcntl.h limits.h pty.h malloc.h memory.h siginfo.h \
+		 string.h strings.h stropts.h sys/types.h sys/wait.h unistd.h \
+		 util.h)
 AC_CHECK_HEADERS(sysexits.h)
 
 # check functions
-AC_CHECK_FUNCS(memcpy memmove memset bcopy bzero strerror strchr strrchr \
-	strstr strtok strrtok index rindex)
+AC_CHECK_FUNCS(memcpy memmove memset strerror strchr \
+		strrchr strstr strtok strrtok index rindex unsetenv)
+AC_CHECK_FUNCS(openpty, openpty=1, openpty=0)
+# openlog() is not in the default libraries.  See if it is in some other lib.
+if test $openpty = 0; then
+  for lib in util; do
+    AC_CHECK_LIB($lib, openpty, [AC_DEFINE(HAVE_OPENPTY)
+		 LIBS="$LIBS -l$lib"; openpty=1; break])
+  done
+fi
+# If we dont have openpty, then look for /dev/ptmx for use by our own
+# openpty().
+if test $openpty = 0; then
+    # This check (partially) comes from expect's configure
+    AC_MSG_CHECKING([for SVR4 style pty allocation])
+    AH_TEMPLATE(HAVE_PTMX, "define this if your o/s has /dev/ptmx")
+    if test -r /dev/ptmx ; then
+	AC_MSG_RESULT(yes)
+	AC_DEFINE(HAVE_PTMX)
+	# Some systems need libpt.a to use /dev/ptmx
+	AC_CHECK_FUNCS(ptsname)
+	if test $ac_cv_func_ptsname+set != set; then
+	    # ptsname is not in the default libraries.
+	    for lib in pt; do
+		AC_CHECK_LIB($lib, ptsname, [LIBS="$LIBS -l$lib"; break])
+	    done
+	fi
+    else
+	AC_MSG_RESULT(no)
+    fi
+    # In OSF/1 case, SVR4 are somewhat different.
+    # Gregory Depp <depp@osf.org> 17Aug93
+    AC_MSG_CHECKING([for OSF/1 style pty allocation])
+    AH_TEMPLATE(HAVE_PTMX_OSF, "define this for OSF/1 ptmx")
+    if test -r /dev/ptmx_bsd ; then
+	AC_DEFINE(HAVE_PTMX_OSF) 
+	AC_MSG_RESULT(yes)
+    else
+	AC_MSG_RESULT(no)
+    fi  
+fi
+
 dnl AC_FUNC_VPRINTF
 
 # type checks
@@ -74,8 +112,7 @@ fi],
 ])
 AM_CONDITIONAL([MK_LCLSTATEDIR], [test "${enable_mk_localstatedir}" = yes])
 
-# Check if user wants us to create LOCALSTATEDIR.  If it's a package-system,
-# they might create it themselves for book-keeping sake; eg: NetBSD
+# Check if user wants us to install sample configurations into the sysconfdir.
 AC_MSG_CHECKING([whether to install sample .conf files in sysconfdir])
 AC_ARG_ENABLE(conf-install,
 	AS_HELP_STRING([--enable-conf-install], [enable install of sample .conf files in sysconfdir (default: yes)]),
@@ -88,6 +125,23 @@ fi],
     enable_conf_install="yes"
 ])
 AM_CONDITIONAL([CONF_INSTALL], [test "${enable_conf_install}" = yes])
+
+# Configure for subversion revision control system instead of CVS.
+AC_MSG_CHECKING([whether subversion])
+AC_ARG_ENABLE(svn,
+	AS_HELP_STRING([--enable-svn], [enable use of subversion instead of cvs]),
+[if test "$enable_svn" = yes; then
+    AC_MSG_RESULT(yes)
+    RCSSYS="svn"
+else
+    AC_MSG_RESULT(no)
+    RCSSYS="cvs"
+fi],
+[AC_MSG_RESULT(no)
+    RCSSYS="cvs"
+])
+AC_SUBST(RCSSYS)
+rd_cv_RCSSYS=$RCSSYS
 
 # Check for a preference for using mail addresses like rancid+group
 # instead of the standard rancid-group
@@ -238,8 +292,13 @@ rd_cv_lg_ping_cmd=$LG_PING_CMD
 ENV_PATH="`dirname $PERLV_PATH`:`dirname $EXPECT_PATH`:`dirname $SENDMAIL`"
 ENV_PATH="$ENV_PATH:`dirname $DIRNAME`:`dirname $DIFF`"
 
-AC_PATH_PROG(CVS,cvs,no)
-ENV_PATH="$ENV_PATH:`dirname $ac_cv_path_CVS`"
+if test $RCSSYS = "cvs" ; then
+    AC_PATH_PROG(CVS,cvs,no)
+    ENV_PATH="$ENV_PATH:`dirname $ac_cv_path_CVS`"
+else
+    AC_PATH_PROG(SVN,svn,no)
+    ENV_PATH="$ENV_PATH:`dirname $ac_cv_path_SVN`"
+fi
 AC_PATH_PROG(COMM,comm,no)
 ENV_PATH="$ENV_PATH:`dirname $ac_cv_path_COMM`"
 AC_PATH_PROG(FIND,find,no)
@@ -278,8 +337,92 @@ AC_CONFIG_FILES(include/version.h)	# this is not a header in the sense of
 					# AC_CONFIG_HEADERS will cause
 					# autoheader to overwrite it, while all
 					# want is simple variable replacement
+# autoheader bits
+AH_TOP([
+#ifndef	CONFIG_H
+#define	CONFIG_H	1
+])
+AH_BOTTOM([
+
+/* damned linux... */
+#ifdef LINUX
+# define _GNU_SOURCE
+#endif
+
+#ifndef __P
+# if STDC_HEADERS
+#  define __P(a)	a
+# else
+#  define __P(a)	()
+# endif
+#endif
+
+#if HAVE_STDLIB_H
+# include <stdlib.h>
+#endif
+
+#if HAVE_UNISTD_H       
+# include <unistd.h>    
+# include <sys/types.h>
+#elif HAVE_SYS_TYPES_H 
+# include <sys/types.h>
+#endif  
+
+#if HAVE_ERRNO_H
+# include <errno.h>
+#endif
+extern int		errno;
+
+#if HAVE_STRING_H
+# include <string.h>    
+#endif
+#if HAVE_STRINGS_H      
+# include <strings.h>
+#endif 
+
+#if ! HAVE_STRERROR
+# define strerror(n)	sys_errlist[n];
+#endif
+
+#if HAVE_SYS_WAIT_H 
+# include <sys/wait.h>
+#endif  
+#ifndef WEXITSTATUS
+# define WEXITSTATUS(stat_val) ((unsigned)(stat_val) >> 8)
+#endif
+#ifndef WIFEXITED
+# define WIFEXITED(stat_val) (((stat_val) & 255) == 0)
+#endif  
+
+#if HAVE_MEMSET
+# define bzero(p,s)	memset(p, 0, s)
+# define bcopy(s,d,l)	memcpy(d, s, l)
+#endif
+
+#if HAVE_INDEX && ! HAVE_STRCHR
+# define index(s,c)	strchr(s,c)
+#endif
+
+#if HAVE_SYSEXITS_H
+# include <sysexits.h>
+#else
+					/* missing sysexits.h */
+# define EX_OK		0
+# define EX_USAGE	64		/* command line usage error */
+# define EX_NOINPUT	66		/* cannot open input */
+# define EX_TEMPFAIL	75		/* temp failure */
+# define EX_OSERR	71		/* system error */
+# define EX_CANTCREAT	73		/* can't create (user) output file */
+# define EX_IOERR	74		/* input/output error */
+# define EX_CONFIG	78		/* configuration error */
+#endif
+
+#endif	/* CONFIG_H */
+])
 AC_CONFIG_HEADERS(include/config.h)
+
 AC_CONFIG_FILES(bin/control_rancid bin/par bin/rancid-fe, [chmod a+x $ac_file])
+AC_CONFIG_FILES(bin/agmrancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/alogin bin/arancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/blogin bin/brancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/cat5rancid bin/clogin bin/rancid, [chmod a+x $ac_file])
@@ -297,6 +440,7 @@ AC_CONFIG_FILES(bin/nslogin bin/nsrancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/prancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/rivlogin bin/rivrancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/rrancid, [chmod a+x $ac_file])
+AC_CONFIG_FILES(bin/srancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/tntlogin bin/tntrancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(bin/xrancid bin/zrancid, [chmod a+x $ac_file])
 AC_CONFIG_FILES(share/rtrfilter, [chmod a+x $ac_file])
